[info]
prefix = 24
network = "192.168.3.0"
gateway = "192.168.3.1"
dns = ["192.168.3.1"]
domain = "guest.binarin.info"


[ipam]
"192.168.3.1" = "usg"
"192.168.3.2" = "octopi"
"192.168.3.3" = "claude-nixos-config"
# "192.168.3.4" = # unallocated
# "192.168.3.5" = # unallocated
# "192.168.3.6" = # unallocated
# "192.168.3.7" = # unallocated
# "192.168.3.8" = # unallocated
# "192.168.3.9" = # unallocated
# "192.168.3.10" = # unallocated
# "192.168.3.11" = # unallocated
# "192.168.3.12" = # unallocated
# "192.168.3.13" = # unallocated
# "192.168.3.14" = # unallocated
# "192.168.3.15" = # unallocated
# "192.168.3.16" = # unallocated
# "192.168.3.17" = # unallocated
# "192.168.3.18" = # unallocated
# "192.168.3.19" = # unallocated
# "192.168.3.20" = # unallocated
# "192.168.3.21" = # unallocated
# "192.168.3.22" = # unallocated
# "192.168.3.23" = # unallocated
# "192.168.3.24" = # unallocated
# "192.168.3.25" = # unallocated
# "192.168.3.26" = # unallocated
# "192.168.3.27" = # unallocated
# "192.168.3.28" = # unallocated
# "192.168.3.29" = # unallocated
# "192.168.3.30" = # unallocated
# "192.168.3.31" = # unallocated
# "192.168.3.32" = # unallocated
# "192.168.3.33" = # unallocated
# "192.168.3.34" = # unallocated
# "192.168.3.35" = # unallocated
# "192.168.3.36" = # unallocated
# "192.168.3.37" = # unallocated
# "192.168.3.38" = # unallocated
# "192.168.3.39" = # unallocated
# "192.168.3.40" = # unallocated
# "192.168.3.41" = # unallocated
# "192.168.3.42" = # unallocated
# "192.168.3.43" = # unallocated
# "192.168.3.44" = # unallocated
# "192.168.3.45" = # unallocated
# "192.168.3.46" = # unallocated
# "192.168.3.47" = # unallocated
# "192.168.3.48" = # unallocated
# "192.168.3.49" = # unallocated
# "192.168.3.50" = # unallocated
# "192.168.3.51" = # unallocated
# "192.168.3.52" = # unallocated
# "192.168.3.53" = # unallocated
# "192.168.3.54" = # unallocated
# "192.168.3.55" = # unallocated
# "192.168.3.56" = # unallocated
# "192.168.3.57" = # unallocated
# "192.168.3.58" = # unallocated
# "192.168.3.59" = # unallocated
# "192.168.3.60" = # unallocated
# "192.168.3.61" = # unallocated
# "192.168.3.62" = # unallocated
# "192.168.3.63" = # unallocated
# "192.168.3.64" = # unallocated
# "192.168.3.65" = # unallocated
# "192.168.3.66" = # unallocated
# "192.168.3.67" = # unallocated
# "192.168.3.68" = # unallocated
# "192.168.3.69" = # unallocated
# "192.168.3.70" = # unallocated
# "192.168.3.71" = # unallocated
# "192.168.3.72" = # unallocated
# "192.168.3.73" = # unallocated
# "192.168.3.74" = # unallocated
# "192.168.3.75" = # unallocated
# "192.168.3.76" = # unallocated
# "192.168.3.77" = # unallocated
# "192.168.3.78" = # unallocated
# "192.168.3.79" = # unallocated
# "192.168.3.80" = # unallocated
# "192.168.3.81" = # unallocated
# "192.168.3.82" = # unallocated
# "192.168.3.83" = # unallocated
# "192.168.3.84" = # unallocated
# "192.168.3.85" = # unallocated
# "192.168.3.86" = # unallocated
# "192.168.3.87" = # unallocated
# "192.168.3.88" = # unallocated
# "192.168.3.89" = # unallocated
# "192.168.3.90" = # unallocated
# "192.168.3.91" = # unallocated
# "192.168.3.92" = # unallocated
# "192.168.3.93" = # unallocated
# "192.168.3.94" = # unallocated
# "192.168.3.95" = # unallocated
# "192.168.3.96" = # unallocated
# "192.168.3.97" = # unallocated
# "192.168.3.98" = # unallocated
# "192.168.3.99" = # unallocated
# "192.168.3.100" = # unallocated
# "192.168.3.101" = # unallocated
# "192.168.3.102" = # unallocated
# "192.168.3.103" = # unallocated
# "192.168.3.104" = # unallocated
# "192.168.3.105" = # unallocated
# "192.168.3.106" = # unallocated
# "192.168.3.107" = # unallocated
# "192.168.3.108" = # unallocated
# "192.168.3.109" = # unallocated
# "192.168.3.110" = # unallocated
# "192.168.3.111" = # unallocated
# "192.168.3.112" = # unallocated
# "192.168.3.113" = # unallocated
# "192.168.3.114" = # unallocated
# "192.168.3.115" = # unallocated
# "192.168.3.116" = # unallocated
# "192.168.3.117" = # unallocated
# "192.168.3.118" = # unallocated
# "192.168.3.119" = # unallocated
# "192.168.3.120" = # unallocated
# "192.168.3.121" = # unallocated
# "192.168.3.122" = # unallocated
# "192.168.3.123" = # unallocated
# "192.168.3.124" = # unallocated
# "192.168.3.125" = # unallocated
# "192.168.3.126" = # unallocated
# "192.168.3.127" = # unallocated
# "192.168.3.128" = # unallocated
# "192.168.3.129" = # unallocated
# "192.168.3.130" = # unallocated
# "192.168.3.131" = # unallocated
# "192.168.3.132" = # unallocated
# "192.168.3.133" = # unallocated
# "192.168.3.134" = # unallocated
# "192.168.3.135" = # unallocated
# "192.168.3.136" = # unallocated
# "192.168.3.137" = # unallocated
# "192.168.3.138" = # unallocated
# "192.168.3.139" = # unallocated
# "192.168.3.140" = # unallocated
# "192.168.3.141" = # unallocated
# "192.168.3.142" = # unallocated
# "192.168.3.143" = # unallocated
# "192.168.3.144" = # unallocated
# "192.168.3.145" = # unallocated
# "192.168.3.146" = # unallocated
# "192.168.3.147" = # unallocated
# "192.168.3.148" = # unallocated
# "192.168.3.149" = # unallocated
# "192.168.3.150" = # unallocated
# "192.168.3.151" = # unallocated
# "192.168.3.152" = # unallocated
# "192.168.3.153" = # unallocated
# "192.168.3.154" = # unallocated
# "192.168.3.155" = # unallocated
# "192.168.3.156" = # unallocated
# "192.168.3.157" = # unallocated
# "192.168.3.158" = # unallocated
# "192.168.3.159" = # unallocated
# "192.168.3.160" = # unallocated
# "192.168.3.161" = # unallocated
# "192.168.3.162" = # unallocated
# "192.168.3.163" = # unallocated
# "192.168.3.164" = # unallocated
# "192.168.3.165" = # unallocated
# "192.168.3.166" = # unallocated
# "192.168.3.167" = # unallocated
# "192.168.3.168" = # unallocated
# "192.168.3.169" = # unallocated
# "192.168.3.170" = # unallocated
# "192.168.3.171" = # unallocated
# "192.168.3.172" = # unallocated
# "192.168.3.173" = # unallocated
# "192.168.3.174" = # unallocated
# "192.168.3.175" = # unallocated
# "192.168.3.176" = # unallocated
# "192.168.3.177" = # unallocated
# "192.168.3.178" = # unallocated
# "192.168.3.179" = # unallocated
# "192.168.3.180" = # unallocated
# "192.168.3.181" = # unallocated
# "192.168.3.182" = # unallocated
# "192.168.3.183" = # unallocated
# "192.168.3.184" = # unallocated
# "192.168.3.185" = # unallocated
# "192.168.3.186" = # unallocated
# "192.168.3.187" = # unallocated
# "192.168.3.188" = # unallocated
# "192.168.3.189" = # unallocated
# "192.168.3.190" = # unallocated
# "192.168.3.191" = # unallocated
# "192.168.3.192" = # unallocated
# "192.168.3.193" = # unallocated
# "192.168.3.194" = # unallocated
# "192.168.3.195" = # unallocated
# "192.168.3.196" = # unallocated
# "192.168.3.197" = # unallocated
# "192.168.3.198" = # unallocated
# "192.168.3.199" = # unallocated
# "192.168.3.200" = # unallocated
# "192.168.3.201" = # unallocated
# "192.168.3.202" = # unallocated
# "192.168.3.203" = # unallocated
# "192.168.3.204" = # unallocated
# "192.168.3.205" = # unallocated
# "192.168.3.206" = # unallocated
# "192.168.3.207" = # unallocated
# "192.168.3.208" = # unallocated
# "192.168.3.209" = # unallocated
# "192.168.3.210" = # unallocated
# "192.168.3.211" = # unallocated
# "192.168.3.212" = # unallocated
# "192.168.3.213" = # unallocated
# "192.168.3.214" = # unallocated
# "192.168.3.215" = # unallocated
# "192.168.3.216" = # unallocated
# "192.168.3.217" = # unallocated
# "192.168.3.218" = # unallocated
# "192.168.3.219" = # unallocated
# "192.168.3.220" = # unallocated
# "192.168.3.221" = # unallocated
# "192.168.3.222" = # unallocated
# "192.168.3.223" = # unallocated
# "192.168.3.224" = # unallocated
# "192.168.3.225" = # unallocated
# "192.168.3.226" = # unallocated
# "192.168.3.227" = # unallocated
# "192.168.3.228" = # unallocated
# "192.168.3.229" = # unallocated
# "192.168.3.230" = # unallocated
# "192.168.3.231" = # unallocated
# "192.168.3.232" = # unallocated
# "192.168.3.233" = # unallocated
# "192.168.3.234" = # unallocated
# "192.168.3.235" = # unallocated
# "192.168.3.236" = # unallocated
# "192.168.3.237" = # unallocated
# "192.168.3.238" = # unallocated
# "192.168.3.239" = # unallocated
# "192.168.3.240" = # unallocated
# "192.168.3.241" = # unallocated
# "192.168.3.242" = # unallocated
# "192.168.3.243" = # unallocated
# "192.168.3.244" = # unallocated
# "192.168.3.245" = # unallocated
# "192.168.3.246" = # unallocated
# "192.168.3.247" = # unallocated
# "192.168.3.248" = # unallocated
# "192.168.3.249" = # unallocated
# "192.168.3.250" = # unallocated
# "192.168.3.251" = # unallocated
# "192.168.3.252" = # unallocated
# "192.168.3.253" = # unallocated
# "192.168.3.254" = # unallocated
