[info]
prefix = 24
network = "192.168.2.0"
gateway = "192.168.2.1"
dns = ["192.168.2.1"]
domain = "home.binarin.info"
searchdomain = "localdomain"


[ipam]
"192.168.2.1" = "usg"
"192.168.2.2" = "monitor"
"192.168.2.3" = "forgejo"
"192.168.2.4" = "lanfear"
"192.168.2.5" = "nix-cache"
"192.168.2.6" = "ishamael"
"192.168.2.7" = "mail"
"192.168.2.8" = "qdevice-kvm"
"192.168.2.9" = "demandred"
"192.168.2.10" = { hostname = "demandred", tags = ["eth"] }
"192.168.2.11" = "docker-on-nixos"
"192.168.2.12" = "galayou-g2"
"192.168.2.13" = "tapo-c100"
"192.168.2.14" = "xray"
"192.168.2.15" = "valak-kvm"
"192.168.2.16" = "qdevice"
"192.168.2.17" = "qdevice-vm"
"192.168.2.18" = "furfur"
"192.168.2.19" = "unifi"
# "192.168.2.20" = # unallocated
"192.168.2.21" = "claude-nixos-config"
# "192.168.2.22" = # unallocated
"192.168.2.23" = "hass-vm"
# "192.168.2.24" = # unallocated
# "192.168.2.25" = # unallocated
"192.168.2.26" = "valak"
# "192.168.2.27" = # unallocated
# "192.168.2.28" = # unallocated
# "192.168.2.29" = # unallocated
# "192.168.2.30" = # unallocated
# "192.168.2.31" = # unallocated
# "192.168.2.32" = # unallocated
# "192.168.2.33" = # unallocated
# "192.168.2.34" = # unallocated
# "192.168.2.35" = # unallocated
# "192.168.2.36" = # unallocated
# "192.168.2.37" = # unallocated
# "192.168.2.38" = # unallocated
# "192.168.2.39" = # unallocated
"192.168.2.40" = "elgato-key-left"
"192.168.2.41" = "elgato-key-right"
"192.168.2.42" = "enphase-envoy"
"192.168.2.43" = "remarkable"
"192.168.2.44" = "raum"
"192.168.2.45" = "raum-kvm"
# "192.168.2.46" = # unallocated
# "192.168.2.47" = # unallocated
# "192.168.2.48" = # unallocated
"192.168.2.49" = "brother-mfc"
"192.168.2.50" = "tinypilot"
# "192.168.2.51" = # unallocated
# "192.168.2.52" = # unallocated
# "192.168.2.53" = # unallocated
# "192.168.2.54" = # unallocated
# "192.168.2.55" = # unallocated
"192.168.2.56" = "prusa-mk4"
"192.168.2.57" = "prusa-xl"
"192.168.2.58" = "brother-scanner"
# "192.168.2.59" = # unallocated
"192.168.2.60" = "shelly-plus-plug-s-1"
"192.168.2.61" = "shelly-plus-plug-s-2"
# "192.168.2.62" = # unallocated
"192.168.2.63" = "shelly-plus-plug-s-3"
"192.168.2.64" = "shelly-plus-plug-s-4"
"192.168.2.65" = "shelly-plus-plug-s-5"
"192.168.2.66" = "shelly-plus-plug-s-6"
# "192.168.2.67" = # unallocated
"192.168.2.68" = "bael"
"192.168.2.69" = "bael-kvm"
"192.168.2.70" = "shelly-plus-plug-s-7"
"192.168.2.71" = "shelly-plus-plug-s-8"
"192.168.2.72" = "shelly-plus-plug-s-9"
"192.168.2.73" = "shelly-plus-plug-s-10"
"192.168.2.74" = "slzb-06"
# "192.168.2.75" = # unallocated
# "192.168.2.76" = # unallocated
"192.168.2.77" = "dnscontrol"
"192.168.2.78" = "xmg1915"
"192.168.2.79" = "media"
"192.168.2.80" = "ulanzi-tc001"
# "192.168.2.81" = # unallocated
# "192.168.2.82" = # unallocated
# "192.168.2.83" = # unallocated
# "192.168.2.84" = # unallocated
# "192.168.2.85" = # unallocated
# "192.168.2.86" = # unallocated
# "192.168.2.87" = # unallocated
# "192.168.2.88" = # unallocated
# "192.168.2.89" = # unallocated
# "192.168.2.90" = # unallocated
# "192.168.2.91" = # unallocated
# "192.168.2.92" = # unallocated
# "192.168.2.93" = # unallocated
# "192.168.2.94" = # unallocated
# "192.168.2.95" = # unallocated
# "192.168.2.96" = # unallocated
# "192.168.2.97" = # unallocated
# "192.168.2.98" = # unallocated
# "192.168.2.99" = # unallocated
# "192.168.2.100" = # unallocated
# "192.168.2.101" = # unallocated
# "192.168.2.102" = # unallocated
# "192.168.2.103" = # unallocated
# "192.168.2.104" = # unallocated
# "192.168.2.105" = # unallocated
# "192.168.2.106" = # unallocated
# "192.168.2.107" = # unallocated
# "192.168.2.108" = # unallocated
# "192.168.2.109" = # unallocated
# "192.168.2.110" = # unallocated
# "192.168.2.111" = # unallocated
# "192.168.2.112" = # unallocated
# "192.168.2.113" = # unallocated
# "192.168.2.114" = # unallocated
# "192.168.2.115" = # unallocated
# "192.168.2.116" = # unallocated
# "192.168.2.117" = # unallocated
# "192.168.2.118" = # unallocated
# "192.168.2.119" = # unallocated
# "192.168.2.120" = # unallocated
# "192.168.2.121" = # unallocated
# "192.168.2.122" = # unallocated
# "192.168.2.123" = # unallocated
# "192.168.2.124" = # unallocated
# "192.168.2.125" = # unallocated
# "192.168.2.126" = # unallocated
# "192.168.2.127" = # unallocated
# "192.168.2.128" = # unallocated
# "192.168.2.129" = # unallocated
# "192.168.2.130" = # unallocated
# "192.168.2.131" = # unallocated
# "192.168.2.132" = # unallocated
# "192.168.2.133" = # unallocated
# "192.168.2.134" = # unallocated
# "192.168.2.135" = # unallocated
# "192.168.2.136" = # unallocated
# "192.168.2.137" = # unallocated
# "192.168.2.138" = # unallocated
# "192.168.2.139" = # unallocated
# "192.168.2.140" = # unallocated
# "192.168.2.141" = # unallocated
# "192.168.2.142" = # unallocated
# "192.168.2.143" = # unallocated
# "192.168.2.144" = # unallocated
# "192.168.2.145" = # unallocated
# "192.168.2.146" = # unallocated
# "192.168.2.147" = # unallocated
# "192.168.2.148" = # unallocated
# "192.168.2.149" = # unallocated
# "192.168.2.150" = # unallocated
# "192.168.2.151" = # unallocated
# "192.168.2.152" = # unallocated
# "192.168.2.153" = # unallocated
# "192.168.2.154" = # unallocated
# "192.168.2.155" = # unallocated
# "192.168.2.156" = # unallocated
# "192.168.2.157" = # unallocated
# "192.168.2.158" = # unallocated
# "192.168.2.159" = # unallocated
# "192.168.2.160" = # unallocated
# "192.168.2.161" = # unallocated
# "192.168.2.162" = # unallocated
# "192.168.2.163" = # unallocated
# "192.168.2.164" = # unallocated
# "192.168.2.165" = # unallocated
# "192.168.2.166" = # unallocated
# "192.168.2.167" = # unallocated
# "192.168.2.168" = # unallocated
# "192.168.2.169" = # unallocated
# "192.168.2.170" = # unallocated
# "192.168.2.171" = # unallocated
# "192.168.2.172" = # unallocated
# "192.168.2.173" = # unallocated
# "192.168.2.174" = # unallocated
# "192.168.2.175" = # unallocated
# "192.168.2.176" = # unallocated
# "192.168.2.177" = # unallocated
# "192.168.2.178" = # unallocated
# "192.168.2.179" = # unallocated
# "192.168.2.180" = # unallocated
# "192.168.2.181" = # unallocated
# "192.168.2.182" = # unallocated
# "192.168.2.183" = # unallocated
# "192.168.2.184" = # unallocated
# "192.168.2.185" = # unallocated
# "192.168.2.186" = # unallocated
# "192.168.2.187" = # unallocated
# "192.168.2.188" = # unallocated
# "192.168.2.189" = # unallocated
# "192.168.2.190" = # unallocated
# "192.168.2.191" = # unallocated
# "192.168.2.192" = # unallocated
# "192.168.2.193" = # unallocated
# "192.168.2.194" = # unallocated
# "192.168.2.195" = # unallocated
# "192.168.2.196" = # unallocated
# "192.168.2.197" = # unallocated
# "192.168.2.198" = # unallocated
# "192.168.2.199" = # unallocated
# "192.168.2.200" = # unallocated
# "192.168.2.201" = # unallocated
# "192.168.2.202" = # unallocated
# "192.168.2.203" = # unallocated
# "192.168.2.204" = # unallocated
# "192.168.2.205" = # unallocated
# "192.168.2.206" = # unallocated
# "192.168.2.207" = # unallocated
# "192.168.2.208" = # unallocated
# "192.168.2.209" = # unallocated
# "192.168.2.210" = # unallocated
# "192.168.2.211" = # unallocated
# "192.168.2.212" = # unallocated
# "192.168.2.213" = # unallocated
# "192.168.2.214" = # unallocated
# "192.168.2.215" = # unallocated
# "192.168.2.216" = # unallocated
# "192.168.2.217" = # unallocated
# "192.168.2.218" = # unallocated
# "192.168.2.219" = # unallocated
# "192.168.2.220" = # unallocated
# "192.168.2.221" = # unallocated
# "192.168.2.222" = # unallocated
# "192.168.2.223" = # unallocated
# "192.168.2.224" = # unallocated
# "192.168.2.225" = # unallocated
# "192.168.2.226" = # unallocated
# "192.168.2.227" = # unallocated
# "192.168.2.228" = # unallocated
# "192.168.2.229" = # unallocated
# "192.168.2.230" = # unallocated
# "192.168.2.231" = # unallocated
# "192.168.2.232" = # unallocated
# "192.168.2.233" = # unallocated
# "192.168.2.234" = # unallocated
# "192.168.2.235" = # unallocated
# "192.168.2.236" = # unallocated
# "192.168.2.237" = # unallocated
# "192.168.2.238" = # unallocated
# "192.168.2.239" = # unallocated
# "192.168.2.240" = # unallocated
# "192.168.2.241" = # unallocated
# "192.168.2.242" = # unallocated
# "192.168.2.243" = # unallocated
# "192.168.2.244" = # unallocated
# "192.168.2.245" = # unallocated
# "192.168.2.246" = # unallocated
# "192.168.2.247" = # unallocated
# "192.168.2.248" = # unallocated
# "192.168.2.249" = # unallocated
# "192.168.2.250" = # unallocated
# "192.168.2.251" = # unallocated
# "192.168.2.252" = # unallocated
# "192.168.2.253" = # unallocated
# "192.168.2.254" = # unallocated
