[info]
prefix = 24
network = "192.168.2.0"
gateway = "192.168.2.1"
dns = ["192.168.2.1"]
domain = "home.binarin.info"

[ipam]
"192.168.2.1" = "usg"
"192.168.2.2" = "monitor"
"192.168.2.3" = "forgejo"
"192.168.2.4" = "lanfear"
"192.168.2.5" = "nix-cache"
"192.168.2.6" = "ishamael"
"192.168.2.7" = "mail"
"192.168.2.8" = "qdevice-kvm"
"192.168.2.9" = "demandred"
"192.168.2.10" = ["demandred", "eth"]
"192.168.2.11" = "docker-on-nixos"
"192.168.2.12" = "galayou-g2"
"192.168.2.13" = "tapo-c100"
"192.168.2.14" = "xray"
"192.168.2.15" = "valak-kvm"
"192.168.2.16" = "qdevice"
"192.168.2.17" = "qdevice-vm"
"192.168.2.18" = "furfur"
"192.168.2.19" = "unifi"
"192.168.2.21" = "claude-nixos-config"
"192.168.2.23" = "hass-vm"
"192.168.2.26" = "valak"
"192.168.2.40" = "elgato-key-left"
"192.168.2.41" = "elgato-key-right"
"192.168.2.42" = "enphase-envoy"
"192.168.2.43" = "remarkable"
"192.168.2.44" = "raum"
"192.168.2.45" = "raum-kvm"
"192.168.2.49" = "brother-mfc"
"192.168.2.50" = "tinypilot"
"192.168.2.56" = "prusa-mk4"
"192.168.2.57" = "prusa-xl"
"192.168.2.58" = "brother-scanner"
"192.168.2.60" = "shelly-plus-plug-s-1"
"192.168.2.61" = "shelly-plus-plug-s-2"
"192.168.2.63" = "shelly-plus-plug-s-3"
"192.168.2.64" = "shelly-plus-plug-s-4"
"192.168.2.65" = "shelly-plus-plug-s-5"
"192.168.2.66" = "shelly-plus-plug-s-6"
"192.168.2.68" = "bael"
"192.168.2.69" = "bael-kvm"
"192.168.2.70" = "shelly-plus-plug-s-7"
"192.168.2.71" = "shelly-plus-plug-s-8"
"192.168.2.72" = "shelly-plus-plug-s-9"
"192.168.2.73" = "shelly-plus-plug-s-10"
"192.168.2.74" = "slzb-06"
"192.168.2.77" = "dnscontrol"
"192.168.2.78" = "xmg1915"
"192.168.2.79" = "media"
"192.168.2.80" = "ulanzi-tc001"
