pve_at_home:
  hosts:
    raum:
    bael:
    valak:

pve:
  children:
    pve_at_home:

qdevices:
  hosts:
    qdevice-vm:

pbs:
  hosts:
    bael:
    pbs-hetzner:

debian_cts:
  hosts:
    paperless:
    docker:
    dnscontrol:
    nextcloud:
    unifi:

debian_baremetal:
  hosts:
    octopi:

debian:
  children:
    debian_cts:
    debian_vms:
    debian_baremetal:


console_autologin:
  children:
    debian_cts:
    debian_vms:

manage_ssh_access:
  children:
    debian_cts:
    debian_vms:
    debian_baremetal:
    pve:
    pbs:

manage_root_ssh_access:
  children:
    pve:
    pbs:

all:
  children:
    pve:
    pbs:
  vars:
    ansible_user: root
