collections:
  - name: victoriametrics.cluster
    version: "2.37.0"
  - name: prometheus.prometheus
    version: "0.27.4"
  - name: ansible.posix
    version: "2.1.0"
  - name: artis3n.tailscale
    version: "1.1.0"

roles:
  - name: aroberts.zfs_exporter
    version: "v1.0.0"
