ssh_keys:
  bael.lynx-lizard.ts.net-pkcs11-root:
    description: root SSH key in pkcs11 at bael - needed for ProxmoxVE operations
    force_install_on:
      bael:
      - root
      qdevice-vm:
      - root
      raum:
      - root
      valak:
      - root
    public_key: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBB2KztRbE1TXYv26vLcezAhNRGw1h2XDzwES0eoARXhtvC2q2JLGNEYyej84wUBi8MkLOmdS1qBxp+24w5dxWDo=
    secure: true
  brother-scanner:
    description: Brother scanner key, for SFTP uploads
    force_install_on:
      paperless:
      - paperless
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCrBq26K0dIo5wDqyMF8FL4NoqP9p4+IJxuTa5bLfEdp/yS9F07orqIfJDx6j+Pb4dRV3F4o9Qe23250SBEmf6z5SY8PxrzkECpx+EzzegkNJkTCgJN0XAep4treDnnO0YqYNtcVCsz+/Td+6aRr/cJGVlKdnqMAUAN35wmBbsc+npwt3yt3K2N11ZmCAQj9sBbS8FCRxFJhBB3h0JiSGeYDQZZle63j2gavDUbBUR0dXuiMnRoitCc1d9Bv3rBMhy4sRKqubcXK48g2CDDxHno5hXd3pyEfbx1N3HdIevV7OnhTUCp6X4KG7h9Sh18ccsJNVr5Awagb5RKAM/9kYbL
    secure: false
  claude-nixos-config:
    description: Let it YOLO
    force_install_on:
      proxmox-test:
      - root
    public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJJEu8TMOeD/d6H+1wt6vKBypE3gGJig1JS+zcdmCq4U
      claude-nixos-config - 2025-02-26
    secure: false
  raum.lynx-lizard.ts.net-pkcs11-root:
    description: root SSH key in pkcs11 at raum - needed for ProxmoxVE operations
    force_install_on:
      qdevice-vm:
      - root
      raum:
      - root
      valak:
      - root
    public_key: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPKyEXbiRblfl23aNjy73yHjFfV/xct885HH4eIzuW3X2VT0BS/jMEFhNJE7eFJE5vO/QIwJ1FKbEonPRGOvNBI=
    secure: true
  termius-pixel:
    description: biometrical key on pixel / termius
    public_key: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGv/Jf+1Xd1nfIGyeEa17VrWrLGDxHKGV0T1tOwtR/IwixUyFqM2jiLuAt+AdPw6xeVoHSeDdd4zMglDE7y5tfI=
    secure: true
    tags:
    - default
    - presence
  termius-tab-s9:
    description: biometrical key on tab s9 / termius
    public_key: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPMpogmbCYL1eZcImgz+QDH5xW5BoTDUP4/daxglmaBul2tp9SFnMT7f73Z9rVF5XSsavVm4j8mLNV6t3I2xCKI=
    secure: true
    tags:
    - default
    - presence
  trezor-root-pve:
    description: Trezor ssh key with root@pve identity
    public_key: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAAHsiCVekjyoPDPOGPJFJ5z9FQUfSmThnGWHABNfjz0APf/qcdHHy+Yj2bG0ICcDbBrE10MJiQjrnYRlKUGvAE=
    secure: true
    tags:
    - default
    - presence
  trezor-trusted-user-ca:
    description: trezor-agent with 'trusted-user-ca' identity
    public_key: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKx4e7PnTrPabkbTwYVsCum+j/Fxgs46NR2ltvgqmUnsJyxVm42rhoqNBp9+1D2Xt0WxikWUBXpe5liSPZzFleo=
    secure: true
    tags:
    - user-ca
  valak.lynx-lizard.ts.net-pkcs11-root:
    description: root SSH key in pkcs11 at valak - needed for ProxmoxVE operations
    force_install_on:
      qdevice-vm:
      - root
      raum:
      - root
      valak:
      - root
    public_key: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBOQGa6V7J3mlk5WFuIUUfjc61ESaCAkmAvzv3vC1qg4A6IJIm083t8MMQFdstFEr6qFrzZZvwyIbWYdN5gUtJ2o=
    secure: true
  yubi-usb-a-5-nfc-fixed:
    description: resident SSH key on Yubikey 5 NFC (usb-a, fixed)
    public_key: sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIEriEHU1OODgpI5oWyeH0zjyUA8N5MsgUiiYIVNXMdQrAAAABHNzaDo=
      usb-a yubikey 5 nfc - fixed  - resident ssh fido2
    secure: true
    tags:
    - default
    - user-ca
    - presence
  yubi-usb-a-5-nfc-keychain:
    description: resident SSH key on Yubikey 5 NFC (usb-a, keychain)
    public_key: sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAINC200GwDhLpi27iCDBppww5QPuRtXACjXsrtJ5hnW0LAAAABHNzaDo=
      usb-a yubikey 5 nfc - keychain  - resident ssh fido2
    secure: true
    tags:
    - default
    - user-ca
    - presence
  yubi-usb-c-5-nfc:
    description: resident SSH key on Yubikey 5 NFC (usb-c, keychain)
    public_key: sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIDaRvW2TCKgLVQuHAv5FyNqQuFidJ+5WhIaV9j6nGU3HAAAABHNzaDo=
      usb-c yubi - residen ssh fido2
    secure: true
    tags:
    - default
    - user-ca
    - presence
